ENV_NAME: 'Unimal-v0'
OUT_DIR: './output'
ENV:
  MODULES: ["Agent", "Terrain", "Objects"]
  WALKER: "./derl/envs/assets/unimal_ant.xml"
  FORWARD_REWARD_WEIGHT: 0.0
  TASK: "point_nav"
  WRAPPERS: ["ReachReward"]
  KEYS_TO_KEEP: ["proprioceptive", "goal"]
TERRAIN:
  TYPES: ["curve_slope"]
  SIZE: [50, 50, 1]
  START_FLAT: 0
  CENTER_FLAT: 50
  TYPES: ["curve_slope"]
  BOUNDARY_WALLS: True